version: '3.6'

services:
  celery:
    build: .
    command: celery -A enferno.tasks worker -B -l info
    depends_on:
      - postgres
      - redis
    entrypoint:
      - /bin/bash
      - /app/bin/celery-entry.sh
    env_file:
      - .env
  
  postgres:
    build:
      dockerfile: ./postgres/Dockerfile
    env_file:
      - .env
    environment:
      PGDATA: /opt/postgres/data
    ports:
      - ${POSTGRES_EXTERNAL_PORT:-5432}:5432
    volumes:
      - db_data:/var/lib/postgresql

  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD:-verystrongpass}
    image: redis:4.0-alpine
    ports:
      - ${REDIS_EXTERNAL_PORT:-6379}:6379
    volumes:
      - redis_data:/var/lib/redis/data

  website:
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - ${WEBSITE_EXTERNAL_PORT:-8000}:5000

volumes:
  db_data: null
  redis_data: null
